### ISSUE TITLE
Support remote IO in KvikIO and cudf

### ISSUE THREAD

**Issue by madsbk** [rapidsai/kvikio#533]
Currently, cudf wheels cannot use the new remote IO feature because of symbols conflicts in libcurl. This is because when buiidling the wheels, kvikio instruct libcurl to statically link to `libcurl.a`, which exposes OpenSSL symbols that conflicts with the ones in CPython. Python segfaults when importing cudf. 
The solution is to make KvikIO a shared library (instead of header-only)  and link to `libcurl.a` statically while excluding its  symbols using `--exclude-libs`.

### Tasks

- [x] Build `libkvikio.so`: https://github.com/rapidsai/kvikio/pull/527
  * Move all use of libcurl to `.cpp`  to avoid symbol conflict. 
  * Fixes https://github.com/rapidsai/kvikio/issues/512
- [x] Update cudf to use `libkvikio.so`: https://github.com/rapidsai/cudf/pull/17239
- [x] Let cudf use the new remote IO feature: https://github.com/rapidsai/cudf/pull/16499

---

CC. @KyleFromNVIDIA @vyasr
